apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: resultserver-deploy
  name: resultserver-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resultserver-deploy
  template:
    metadata:
      labels:
        app: resultserver-deploy
    spec:
      containers:
      - image: sezar02/resultserver
        name: resultserver
        ports:
        - containerPort: 80
        env:
        - name: MYSQL_PASSWORD
        # value: juliet
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql_admin_password
        envFrom:
          - configMapRef:
              name: servers-configmap      