apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: webserver-deploy
  name: webserver-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webserver-deploy
    spec:
      containers:
      - image: johnws/webserver
        name: webserver
        resources: {}
status: {}
